// ==================== 高频短语数据库 ====================

export const phraseDB = [
    { id: 1, phrase: "take advantage of", meaning: "利用", example: "Take advantage of this opportunity.", category: "动词短语" },
    { id: 2, phrase: "in terms of", meaning: "就…而言", example: "In terms of quality, this is the best.", category: "介词短语" },
    { id: 3, phrase: "as a result", meaning: "结果，因此", example: "As a result, sales increased.", category: "过渡词" },
    { id: 4, phrase: "on the contrary", meaning: "相反", example: "On the contrary, it proved beneficial.", category: "过渡词" },
    { id: 5, phrase: "in addition to", meaning: "除…之外", example: "In addition to English, she speaks French.", category: "介词短语" },
    { id: 6, phrase: "by means of", meaning: "通过…方式", example: "Communicate by means of email.", category: "介词短语" },
    { id: 7, phrase: "in favor of", meaning: "支持，有利于", example: "I am in favor of this proposal.", category: "介词短语" },
    { id: 8, phrase: "in regard to", meaning: "关于", example: "In regard to your question, here is the answer.", category: "介词短语" },
    { id: 9, phrase: "at the expense of", meaning: "以…为代价", example: "Success came at the expense of health.", category: "介词短语" },
    { id: 10, phrase: "in contrast to", meaning: "与…对比", example: "In contrast to last year, profits have risen.", category: "过渡词" },
    { id: 11, phrase: "account for", meaning: "解释；占(比例)", example: "This accounts for 30% of the total.", category: "动词短语" },
    { id: 12, phrase: "apply to", meaning: "适用于；申请", example: "This rule applies to everyone.", category: "动词短语" },
    { id: 13, phrase: "attribute to", meaning: "归因于", example: "The success was attributed to hard work.", category: "动词短语" },
    { id: 14, phrase: "benefit from", meaning: "从…受益", example: "Children benefit from early education.", category: "动词短语" },
    { id: 15, phrase: "come up with", meaning: "提出；想出", example: "She came up with a brilliant idea.", category: "动词短语" },
    { id: 16, phrase: "consist of", meaning: "由…组成", example: "The team consists of five members.", category: "动词短语" },
    { id: 17, phrase: "contribute to", meaning: "有助于；贡献", example: "Exercise contributes to good health.", category: "动词短语" },
    { id: 18, phrase: "cope with", meaning: "处理，应对", example: "She can cope with stress well.", category: "动词短语" },
    { id: 19, phrase: "deal with", meaning: "处理；涉及", example: "We must deal with the problem immediately.", category: "动词短语" },
    { id: 20, phrase: "depend on", meaning: "依赖；取决于", example: "Success depends on preparation.", category: "动词短语" },
    { id: 21, phrase: "derive from", meaning: "源自；从…得到", example: "The word derives from Latin.", category: "动词短语" },
    { id: 22, phrase: "devote to", meaning: "致力于", example: "She devoted her life to science.", category: "动词短语" },
    { id: 23, phrase: "focus on", meaning: "集中于", example: "We should focus on the main issue.", category: "动词短语" },
    { id: 24, phrase: "give rise to", meaning: "引起，导致", example: "The news gave rise to panic.", category: "动词短语" },
    { id: 25, phrase: "interfere with", meaning: "干扰；干涉", example: "Noise interferes with concentration.", category: "动词短语" },
    { id: 26, phrase: "lead to", meaning: "导致，通向", example: "Hard work leads to success.", category: "动词短语" },
    { id: 27, phrase: "make use of", meaning: "利用", example: "Make good use of your time.", category: "动词短语" },
    { id: 28, phrase: "participate in", meaning: "参加", example: "She participates in many activities.", category: "动词短语" },
    { id: 29, phrase: "put forward", meaning: "提出", example: "He put forward a new theory.", category: "动词短语" },
    { id: 30, phrase: "refer to", meaning: "提及；参考", example: "Please refer to the manual.", category: "动词短语" },
    { id: 31, phrase: "rely on", meaning: "依靠，依赖", example: "Don't rely on luck alone.", category: "动词短语" },
    { id: 32, phrase: "result in", meaning: "导致", example: "The accident resulted in heavy traffic.", category: "动词短语" },
    { id: 33, phrase: "set up", meaning: "建立；设立", example: "They set up a new company.", category: "动词短语" },
    { id: 34, phrase: "take into account", meaning: "考虑到", example: "Take all factors into account.", category: "动词短语" },
    { id: 35, phrase: "turn out", meaning: "结果是；证明是", example: "Everything turned out fine.", category: "动词短语" },
    { id: 36, phrase: "work out", meaning: "解决；计算出；锻炼", example: "We need to work out a solution.", category: "动词短语" },
    { id: 37, phrase: "carry out", meaning: "执行，实施", example: "They carried out the experiment.", category: "动词短语" },
    { id: 38, phrase: "figure out", meaning: "弄清楚，算出", example: "Figure out the answer yourself.", category: "动词短语" },
    { id: 39, phrase: "point out", meaning: "指出", example: "He pointed out the mistake.", category: "动词短语" },
    { id: 40, phrase: "bring about", meaning: "引起，带来", example: "Technology brought about changes.", category: "动词短语" },
    { id: 41, phrase: "end up", meaning: "最终处于", example: "We ended up staying at home.", category: "动词短语" },
    { id: 42, phrase: "keep up with", meaning: "跟上，保持同步", example: "Keep up with the latest news.", category: "动词短语" },
    { id: 43, phrase: "look forward to", meaning: "期待", example: "I look forward to meeting you.", category: "动词短语" },
    { id: 44, phrase: "pass away", meaning: "去世", example: "He passed away peacefully.", category: "动词短语" },
    { id: 45, phrase: "put up with", meaning: "忍受", example: "I can't put up with the noise.", category: "动词短语" },
    { id: 46, phrase: "run out of", meaning: "用完，耗尽", example: "We ran out of time.", category: "动词短语" },
    { id: 47, phrase: "take off", meaning: "起飞；脱下；成功", example: "The plane took off on time.", category: "动词短语" },
    { id: 48, phrase: "a variety of", meaning: "各种各样的", example: "A variety of options are available.", category: "固定搭配" },
    { id: 49, phrase: "in the light of", meaning: "鉴于；根据", example: "In the light of recent events.", category: "介词短语" },
    { id: 50, phrase: "on the basis of", meaning: "基于", example: "Decisions made on the basis of facts.", category: "介词短语" },
    { id: 51, phrase: "as opposed to", meaning: "与…相反；而不是", example: "Quality as opposed to quantity.", category: "过渡词" },
    { id: 52, phrase: "for the sake of", meaning: "为了…起见", example: "For the sake of simplicity.", category: "介词短语" },
    { id: 53, phrase: "in accordance with", meaning: "按照，根据", example: "In accordance with the rules.", category: "介词短语" },
    { id: 54, phrase: "in comparison with", meaning: "与…相比", example: "In comparison with last year.", category: "介词短语" },
    { id: 55, phrase: "in conjunction with", meaning: "与…一起", example: "Used in conjunction with other methods.", category: "介词短语" },
    { id: 56, phrase: "in relation to", meaning: "关于；与…相关", example: "In relation to the topic discussed.", category: "介词短语" },
    { id: 57, phrase: "in response to", meaning: "作为对…的回应", example: "In response to your inquiry.", category: "介词短语" },
    { id: 58, phrase: "with regard to", meaning: "关于，至于", example: "With regard to your application.", category: "介词短语" },
    { id: 59, phrase: "as far as", meaning: "就…而言", example: "As far as I know, it's true.", category: "过渡词" },
    { id: 60, phrase: "not only…but also…", meaning: "不仅…而且…", example: "Not only fast but also reliable.", category: "固定搭配" },
    { id: 61, phrase: "neither…nor…", meaning: "既不…也不…", example: "Neither cheap nor effective.", category: "固定搭配" },
    { id: 62, phrase: "whether…or…", meaning: "是…还是…；无论", example: "Whether you agree or not.", category: "固定搭配" },
    { id: 63, phrase: "the more…the more…", meaning: "越…越…", example: "The more you practice, the better.", category: "固定搭配" },
    { id: 64, phrase: "it is…that…", meaning: "正是…(强调句)", example: "It is education that matters most.", category: "固定搭配" },
    { id: 65, phrase: "no sooner…than…", meaning: "一…就…", example: "No sooner had I arrived than it rained.", category: "固定搭配" },
    { id: 66, phrase: "would rather…than…", meaning: "宁愿…而不…", example: "I would rather walk than take a bus.", category: "固定搭配" },
    { id: 67, phrase: "at all costs", meaning: "不惜任何代价", example: "We must avoid war at all costs.", category: "固定搭配" },
    { id: 68, phrase: "beyond control", meaning: "无法控制", example: "The situation is beyond control.", category: "固定搭配" },
    { id: 69, phrase: "in vain", meaning: "徒劳地", example: "All efforts were in vain.", category: "固定搭配" },
    { id: 70, phrase: "on purpose", meaning: "故意地", example: "He did it on purpose.", category: "固定搭配" },
    { id: 71, phrase: "out of date", meaning: "过时的", example: "The information is out of date.", category: "固定搭配" },
    { id: 72, phrase: "out of order", meaning: "出故障的", example: "The elevator is out of order.", category: "固定搭配" },
    { id: 73, phrase: "out of reach", meaning: "够不着；无法达到", example: "The goal seems out of reach.", category: "固定搭配" },
    { id: 74, phrase: "to some extent", meaning: "在某种程度上", example: "To some extent, I agree.", category: "固定搭配" },
    { id: 75, phrase: "under control", meaning: "处于控制之下", example: "The fire is under control.", category: "固定搭配" },
    { id: 76, phrase: "under way", meaning: "在进行中", example: "The project is under way.", category: "固定搭配" },
    { id: 77, phrase: "by and large", meaning: "大体上", example: "By and large, the plan was successful.", category: "固定搭配" },
    { id: 78, phrase: "in general", meaning: "一般来说", example: "In general, people are honest.", category: "过渡词" },
    { id: 79, phrase: "on average", meaning: "平均而言", example: "On average, we sleep eight hours.", category: "过渡词" },
    { id: 80, phrase: "for instance", meaning: "例如", example: "For instance, consider this case.", category: "过渡词" },
    { id: 81, phrase: "in particular", meaning: "尤其，特别地", example: "In particular, the last chapter.", category: "过渡词" },
    { id: 82, phrase: "in other words", meaning: "换句话说", example: "In other words, you're wrong.", category: "过渡词" },
    { id: 83, phrase: "in conclusion", meaning: "总之", example: "In conclusion, we agree.", category: "过渡词" },
    { id: 84, phrase: "in short", meaning: "简而言之", example: "In short, the plan failed.", category: "过渡词" },
    { id: 85, phrase: "above all", meaning: "最重要的是", example: "Above all, be honest.", category: "过渡词" },
    { id: 86, phrase: "after all", meaning: "毕竟；终究", example: "After all, we are only human.", category: "过渡词" },
    { id: 87, phrase: "all in all", meaning: "总的来说", example: "All in all, it was a good trip.", category: "过渡词" },
    { id: 88, phrase: "as a whole", meaning: "总体上", example: "The country as a whole prospered.", category: "过渡词" },
    { id: 89, phrase: "at first", meaning: "起初", example: "At first, I didn't believe him.", category: "过渡词" },
    { id: 90, phrase: "for the first time", meaning: "第一次", example: "For the first time, I understood.", category: "固定搭配" },
    { id: 91, phrase: "from now on", meaning: "从现在开始", example: "From now on, be punctual.", category: "固定搭配" },
    { id: 92, phrase: "in the future", meaning: "在未来", example: "In the future, things will change.", category: "固定搭配" },
    { id: 93, phrase: "in the meantime", meaning: "与此同时", example: "In the meantime, keep working.", category: "过渡词" },
    { id: 94, phrase: "so far", meaning: "到目前为止", example: "So far, everything is fine.", category: "过渡词" },
    { id: 95, phrase: "all the same", meaning: "仍然；都一样", example: "All the same, I'd rather stay.", category: "固定搭配" },
    { id: 96, phrase: "apart from", meaning: "除…外", example: "Apart from the cost, it's perfect.", category: "介词短语" },
    { id: 97, phrase: "as for", meaning: "至于", example: "As for me, I prefer coffee.", category: "介词短语" },
    { id: 98, phrase: "as to", meaning: "关于，至于", example: "As to the details, we'll discuss later.", category: "介词短语" },
    { id: 99, phrase: "except for", meaning: "除…外", example: "Except for a few errors, it's good.", category: "介词短语" },
    { id: 100, phrase: "in case of", meaning: "万一；如果", example: "In case of emergency, call 110.", category: "介词短语" },
    { id: 101, phrase: "in charge of", meaning: "负责", example: "Who is in charge of this project?", category: "介词短语" },
    { id: 102, phrase: "in face of", meaning: "面对", example: "In face of difficulty, stay calm.", category: "介词短语" },
    { id: 103, phrase: "in honor of", meaning: "为纪念；向…表示敬意", example: "A party in honor of the guest.", category: "介词短语" },
    { id: 104, phrase: "in memory of", meaning: "纪念", example: "A statue in memory of the hero.", category: "介词短语" },
    { id: 105, phrase: "in place of", meaning: "代替", example: "Use milk in place of cream.", category: "介词短语" },
    { id: 106, phrase: "in search of", meaning: "寻找", example: "Travel in search of adventure.", category: "介词短语" },
    { id: 107, phrase: "in spite of", meaning: "尽管", example: "In spite of the rain, we went out.", category: "介词短语" },
    { id: 108, phrase: "in view of", meaning: "鉴于", example: "In view of the situation, we'll wait.", category: "介词短语" },
    { id: 109, phrase: "on behalf of", meaning: "代表", example: "On behalf of the team, thank you.", category: "介词短语" },
    { id: 110, phrase: "on the point of", meaning: "正要…的时候", example: "I was on the point of leaving.", category: "介词短语" },
    { id: 111, phrase: "with a view to", meaning: "为了，目的在于", example: "Measures with a view to improvement.", category: "介词短语" },
    { id: 112, phrase: "catch up with", meaning: "赶上", example: "I need to catch up with my work.", category: "动词短语" },
    { id: 113, phrase: "drop out of", meaning: "退出；辍学", example: "He dropped out of school.", category: "动词短语" },
    { id: 114, phrase: "get along with", meaning: "与…相处", example: "She gets along with everyone.", category: "动词短语" },
    { id: 115, phrase: "get rid of", meaning: "摆脱；除掉", example: "Get rid of bad habits.", category: "动词短语" },
    { id: 116, phrase: "live up to", meaning: "不辜负；达到", example: "Live up to expectations.", category: "动词短语" },
    { id: 117, phrase: "look down on", meaning: "看不起", example: "Don't look down on others.", category: "动词短语" },
    { id: 118, phrase: "look up to", meaning: "尊敬", example: "I look up to my father.", category: "动词短语" },
    { id: 119, phrase: "make up for", meaning: "弥补", example: "Make up for lost time.", category: "动词短语" },
    { id: 120, phrase: "stand up for", meaning: "支持；维护", example: "Stand up for your rights.", category: "动词短语" },
    { id: 121, phrase: "on account of", meaning: "因为", example: "Delayed on account of weather.", category: "介词短语" },
    { id: 122, phrase: "by virtue of", meaning: "凭借", example: "Success by virtue of hard work.", category: "介词短语" },
    { id: 123, phrase: "in the event of", meaning: "如果…发生", example: "In the event of fire, use stairs.", category: "介词短语" },
    { id: 124, phrase: "prior to", meaning: "在…之前", example: "Prior to the meeting, prepare notes.", category: "介词短语" },
    { id: 125, phrase: "regardless of", meaning: "无论，不管", example: "Regardless of the cost, do it.", category: "介词短语" },
    { id: 126, phrase: "owing to", meaning: "由于，因为", example: "Owing to bad weather, we canceled.", category: "介词短语" },
    { id: 127, phrase: "due to", meaning: "由于", example: "Delay due to technical issues.", category: "介词短语" },
    { id: 128, phrase: "thanks to", meaning: "多亏，由于", example: "Thanks to your help, we succeeded.", category: "介词短语" },
    { id: 129, phrase: "along with", meaning: "连同，与…一起", example: "Along with the letter, photos included.", category: "介词短语" },
    { id: 130, phrase: "together with", meaning: "连同，和…一起", example: "Together with my friends, I traveled.", category: "介词短语" },
    { id: 131, phrase: "as well as", meaning: "也，和…一样", example: "She sings as well as dances.", category: "固定搭配" },
    { id: 132, phrase: "rather than", meaning: "而不是", example: "Focus on quality rather than quantity.", category: "过渡词" },
    { id: 133, phrase: "other than", meaning: "除了", example: "Other than that, everything is fine.", category: "介词短语" },
    { id: 134, phrase: "more than", meaning: "超过；不仅仅", example: "More than just a friend.", category: "固定搭配" },
    { id: 135, phrase: "less than", meaning: "少于", example: "In less than an hour.", category: "固定搭配" },
    { id: 136, phrase: "no more than", meaning: "仅仅，不超过", example: "No more than five people attended.", category: "固定搭配" },
    { id: 137, phrase: "no less than", meaning: "多达，不少于", example: "No less than fifty students joined.", category: "固定搭配" },
    { id: 138, phrase: "more or less", meaning: "或多或少；大约", example: "More or less the same result.", category: "固定搭配" },
    { id: 139, phrase: "once in a while", meaning: "偶尔", example: "We meet once in a while.", category: "固定搭配" },
    { id: 140, phrase: "on the whole", meaning: "总的来说", example: "On the whole, it was successful.", category: "过渡词" },
    { id: 141, phrase: "at any rate", meaning: "无论如何", example: "At any rate, we must continue.", category: "固定搭配" },
    { id: 142, phrase: "by no means", meaning: "绝不", example: "By no means is this an easy task.", category: "固定搭配" },
    { id: 143, phrase: "in no way", meaning: "绝不，完全不", example: "In no way can we accept this.", category: "固定搭配" },
    { id: 144, phrase: "now that", meaning: "既然", example: "Now that you're here, let's start.", category: "过渡词" },
    { id: 145, phrase: "even if", meaning: "即使", example: "Even if it rains, we'll go.", category: "过渡词" },
    { id: 146, phrase: "as if", meaning: "好像", example: "He talks as if he knows everything.", category: "过渡词" },
    { id: 147, phrase: "only if", meaning: "只有当", example: "Only if you promise to be careful.", category: "固定搭配" },
    { id: 148, phrase: "if only", meaning: "要是…就好了", example: "If only I had known earlier.", category: "固定搭配" },
    { id: 149, phrase: "what's more", meaning: "而且", example: "It's cheap and, what's more, durable.", category: "过渡词" },
    { id: 150, phrase: "that is to say", meaning: "也就是说", example: "That is to say, we need more time.", category: "过渡词" },
];
